version: '3.9'

services:
  app:
    container_name: docker-compose-app
    build:
      context: .
    volumes:
      - ./app:/code/app
    env_file:
      - env/.env
    ports:
      - "8000:80"
  postgresql:
    image: postgres
    container_name: docker-compose-postgresql
    env_file:
      - development/db/postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - ./development/db/postgres/pgdata:/var/lib/postgresql/data

#  mysql:
#    image: mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=mysqlsecret
#    volumes:
#      - ./db/mysql:/var/lib/mysql
#    ports:
#      - "3306:3306"
#  mongodb:
#    image: mongo:4.0
#    ports:
#      - "27017:27017"
#    command: [ "--sslMode", "requireSSL", "--sslPEMKeyFile", "/usr/local/share/ca-certificates/mongodb.pem" ]
#    volumes:
#      - ./ca-certs:/usr/local/share/ca-certificates
#      - ~/apps/mongo4:/data/db
#    environment:
#      - MONGO_INITDB_ROOT_USERNAME=citizix
#      - MONGO_INITDB_ROOT_PASSWORD=S3cret
#
#  cache:
#    image: redis:alpine
##    container_name: cache
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./redis.conf:/usr/local/etc/redis/redis.conf
#    command: redis-server /usr/local/etc/redis/redis.conf
#
